    <!-- application/views/scripts/employee/index.phtml -->
     
    <p><a href="<?php echo $this->url(
        array(
            'controller' => 'Employee',
            'action'     => 'sign'
        ),
        'default',
        true) ?>">Sign Our Employee</a></p>
     
    Employee Entries: <br />
    <div><table>
    	<tr><td>ID</td> <td>Name</td><td>BankOwner</td><td>BackownID</td><td>BackCardID</td>
    	<td>Start Date</td><td>Expired</td><td>Email</td><td>Phone</td></tr>
    	<?php foreach ($this->entries as $entry): ?>
    	<tr>
    		<td><?php echo $this->escape($entry->Id) ?></td>
        	<td><?php echo $this->escape($entry->Name) ?></td>
        	<td><?php echo $this->escape($entry->BankOwner) ?></td>
        	<td><?php echo $this->escape($entry->BankOwnerID) ?></td>
        	<td><?php echo $this->escape($entry->BankcardID) ?></td>
        	<td><?php echo $this->escape($entry->StartDate) ?></td>
        	<td><?php echo $this->escape($entry->IsExpired) ?></td>
        	<td><?php echo $this->escape($entry->Email) ?></td>
        	<td><?php echo $this->escape($entry->Phone) ?></td>
        </tr>
    	<?php endforeach ?>
    </table></div>
   