    <p><a href="<?php echo $this->url(
        array(
            'controller' => 'solution',
            'action'     => 'add'
        ),
        'default',
        true) ?>">Add a solution </a></p>
     
    Employee Entries: <br />
    <div><table>
    	<tr><td>ID</td> <td>Inventor</td><td>title</td><td>RFI</td><td>submit date</td>
    	<td>SR accept </td></tr>
    	<?php foreach ($this->entries as $entry): ?>
    	<tr>
    		<td><?php echo $this->escape($entry->id) ?></td>
        	<td><?php echo $this->escape($entry->inventor) ?></td>
        	<td><?php echo $this->escape($entry->title) ?></td>
        	<td><?php echo $this->escape($entry->RFI) ?></td>
        	<td><?php echo $this->escape($entry->submitDate) ?></td>
        	<td><?php echo $this->escape($entry->accept) ?></td>
        </tr>
    	<?php endforeach ?>
    </table></div>