      <!-- application/views/scripts/user/index.phtml -->
      <p><a href="<?php echo $this->url(
          array(
              'controller' => 'user',
              'action'     => 'sign'
          ),
          'default',true) ?>">Sign Our Guestbook</a></p>
      Guestbook Entries: <br />
      <dl>
          <?php foreach ($this->entries as $entry): ?>
          <dt><?php echo $this->escape($entry->FirstName) ?></dt>
          <dd><?php echo $this->escape($entry->LastName) ?></dd>
          <dd><?php echo $this->escape($entry->UserName) ?></dd>
          <?php endforeach ?>
      </dl>